on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: build

jobs:
  build:
    name: Build
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      id: build
      run: |
        $currentDir = (Get-Location).Path
        docker run -v "${currentDir}:C:\build\app" magicxor/radstudio:xe8upd1-delphi-net3.5-ltsc2019 msbuild /t:build C:\build\app\ArrayLinq.groupproj
